name: GitHub Snake Game 🐍

on:
  # Runs every 6 hours as backup
  schedule:
    - cron: "0 */6 * * *"

  # Allows manual trigger from GitHub Actions tab
  workflow_dispatch:

  # Runs on every push to any branch
  push:
    branches:
      - '**'

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: snake-game
      cancel-in-progress: true

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the GitHub Contributions Snake
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Deploy to the output branch
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update GitHub Snake animation [skip ci]"
